FROM gerasim13/golang
MAINTAINER Pavel Litvinenko <gerasim13@gmail.com>

RUN /bin/bash go-wrapper download github.com/compose/transporter/...
RUN /bin/bash go-wrapper install github.com/compose/transporter/...
